image: registry.bappli.com/images/php/8.0:latest

cache:
  paths:
    - vendor/

before_script:
  - composer install

code-coverage:
  stage: quality
  script:
    ## Only possible with official php image
    - docker-php-ext-enable xdebug || true
    - vendor/bin/phpunit --configuration $CI_PROJECT_DIR/phpunit.xml.dist --coverage-text --colors=never

coding-standard:
  stage: test
  script:
    - vendor/bin/phpcs --standard=ITRocks --extensions=php $CI_PROJECT_DIR/ITRocks

test:
  stage: test
  script:
    - vendor/bin/phpunit --configuration $CI_PROJECT_DIR/phpunit.xml.dist

stages:
  - test
  - quality
