image: registry.bappli.com/images/php-7.2:latest

cache:
  paths:
    - vendor/

before_script:
  - php composer.phar install

code-coverage:
  stage: quality
  script:
    - docker-php-ext-enable xdebug
    - vendor/bin/phpunit --configuration $CI_PROJECT_DIR/phpunit.xml.dist --coverage-text --colors=never

coding-standard:
  stage: test
  script:
    - vendor/bin/phpcs --standard=ITRocks --extensions=php $CI_PROJECT_DIR/ITRocks

test:
  stage: test
  script:
    - vendor/bin/phpunit --configuration $CI_PROJECT_DIR/phpunit.xml.dist

stages:
  - test
  - quality
