image: php:7.1

cache:
  paths:
    - vendor/

before_script:
  - apt-get update -yqq && apt-get install -y git zip

  # Install and run Composer
  - curl -sS https://getcomposer.org/installer | php
  - php composer.phar install

coding-standard:
  script:
    - vendor/bin/phpcs --config-set installed_paths $CI_PROJECT_DIR/ITRocks
    - vendor/bin/phpcs --standard=ITRocks $CI_PROJECT_DIR/ITRocks/Sniffs
    - vendor/bin/phpcs --standard=ITRocks $CI_PROJECT_DIR/ITRocks/Tests

test:
  script:
    - vendor/bin/phpunit $CI_PROJECT_DIR/ITRocks/Tests --colors=never
