<?php
namespace ITRocks\Coding_Standard\Tests\Formatting;

/**
 * Class Foo
 */
class Foo
{
	//------------------------------------------------------------------------------------------- bar
	/**
	 *
	 */
	function bar()
	{

	}

	//---------------------------------------------------------------------------------------- barfoo
	/**
	 *
	 */
	function barfoo($foobar1, $foobar2, $foobar3, $foobar4, $foobar5, $foobar6, $foobar7, $foobar8, $foobar9,
		$foobar10, $foobar11, $foobar12, $foobar13, $foobar14) {

	}

	//------------------------------------------------------------------------------------------- foo
	/**
	 *
	 */
	function foo()
	{

	}

	//---------------------------------------------------------------------------------------- fooBar
	/**
	 *
	 */
	function fooBar($foobar1, $foobar2, $foobar3, $foobar4, $foobar5, $foobar6, $foobar7, $foobar8, $foobar9,
		$foobar10, $foobar11, $foobar12, $foobar13, $foobar14
	) {

	}

	//--------------------------------------------------------------------------------------- fooBar2
	/**
	 *
	 */
	function fooBar2($foobar1, $foobar2, $foobar3, $foobar4, $foobar5, $foobar6, $foobar7, $foobar8, $foobar9,
		$foobar10, $foobar11, $foobar12, $foobar13, $foobar14
	) {

	}

}
